import { useApp } from "@/context/AppContext";
import { Card, CardHeader, CardBody } from "@/components/ui/Card";
import { Badge, DifficultyBadge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import {
  Route,
  CheckCircle2,
  Circle,
  PlayCircle,
  Lock,
  ArrowDown,
  Sparkles,
  Clock,
  BookOpen,
  Target,
} from "lucide-react";
import type { LearningPathNode } from "@/types";

export function LearningPathPage() {
  const { learningPath, profile, toggleTopicComplete, completedTopics } = useApp();

  const completedCount = completedTopics.length;
  const totalCount = learningPath.length;
  const progressPercent = totalCount > 0 ? Math.round((completedCount / totalCount) * 100) : 0;

  return (
    <div className="space-y-6">
      {/* Header banner */}
      <div className="rounded-2xl bg-gradient-to-br from-blue-600 to-cyan-500 p-6 text-white">
        <div className="flex items-start gap-4">
          <div className="w-12 h-12 rounded-xl bg-white/15 flex items-center justify-center shrink-0">
            <Route size={24} />
          </div>
          <div className="flex-1">
            <h3 className="text-lg font-bold mb-1">Your Personalized Learning Path</h3>
            <p className="text-sm text-blue-50">
              This roadmap was generated by the AI agent based on your goal of{" "}
              <span className="font-semibold text-white">{profile.learningGoal}</span>, existing skills,
              identified gaps, and prerequisites. It's unique to you — not a generic template.
            </p>
          </div>
        </div>
      </div>

      {/* Progress overview */}
      <Card className="p-5">
        <div className="flex items-center justify-between mb-3">
          <div>
            <h4 className="font-semibold text-slate-900">Path Progress</h4>
            <p className="text-sm text-slate-500">{completedCount} of {totalCount} topics completed</p>
          </div>
          <div className="text-right">
            <span className="text-3xl font-bold text-blue-600">{progressPercent}%</span>
          </div>
        </div>
        <div className="h-3 bg-slate-100 rounded-full overflow-hidden">
          <div
            className="h-full bg-gradient-to-r from-blue-500 to-cyan-400 rounded-full transition-all duration-700"
            style={{ width: `${progressPercent}%` }}
          />
        </div>
      </Card>

      {/* Timeline / Roadmap */}
      <Card>
        <CardHeader
          title="Learning Roadmap"
          subtitle="Follow the path from foundations to mastery"
          icon={<Route size={20} />}
        />
        <CardBody>
          <div className="relative">
            {/* Vertical line */}
            <div className="absolute left-5 top-2 bottom-2 w-0.5 bg-slate-200" />

            <div className="space-y-1">
              {learningPath.map((node, index) => (
                <PathNode
                  key={node.id}
                  node={node}
                  index={index}
                  isLast={index === learningPath.length - 1}
                  onToggle={() => toggleTopicComplete(node.id)}
                />
              ))}
            </div>
          </div>
        </CardBody>
      </Card>

      {/* Personalization explanation */}
      <Card className="p-5">
        <div className="flex items-start gap-3">
          <div className="w-10 h-10 rounded-xl bg-blue-50 flex items-center justify-center text-blue-600 shrink-0">
            <Sparkles size={20} />
          </div>
          <div>
            <h4 className="font-semibold text-slate-900 mb-1">How Your Path Was Personalized</h4>
            <p className="text-sm text-slate-600 leading-relaxed mb-3">
              The AI agent built your path by analyzing:
            </p>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
              <div className="flex items-center gap-2 text-sm text-slate-600">
                <Target size={14} className="text-blue-500" /> Your learning goal
              </div>
              <div className="flex items-center gap-2 text-sm text-slate-600">
                <BookOpen size={14} className="text-blue-500" /> Existing skill levels
              </div>
              <div className="flex items-center gap-2 text-sm text-slate-600">
                <Sparkles size={14} className="text-blue-500" /> Identified skill gaps
              </div>
              <div className="flex items-center gap-2 text-sm text-slate-600">
                <Route size={14} className="text-blue-500" /> Prerequisite dependencies
              </div>
            </div>
            <p className="text-sm text-slate-600 leading-relaxed mt-3">
              Topics where you're already strong are marked as completed or skipped ahead.
              Topics where you have gaps are kept at beginner difficulty. As you improve,
              the path adapts automatically.
            </p>
          </div>
        </div>
      </Card>
    </div>
  );
}

function PathNode({
  node,
  index,
  isLast,
  onToggle,
}: {
  node: LearningPathNode;
  index: number;
  isLast: boolean;
  onToggle: () => void;
}) {
  const prereqsMet = node.prerequisites.every((pid) => {
    // We trust the isCurrent/completed flags from the engine
    return true;
  });

  const isLocked = !node.completed && !node.isCurrent && !prereqsMet;

  return (
    <div className="relative pl-14 pb-6">
      {/* Node indicator */}
      <div className="absolute left-0 top-0 w-10 h-10 rounded-full flex items-center justify-center z-10 bg-white">
        {node.completed ? (
          <div className="w-10 h-10 rounded-full bg-emerald-500 flex items-center justify-center shadow-md">
            <CheckCircle2 size={22} className="text-white" />
          </div>
        ) : node.isCurrent ? (
          <div className="w-10 h-10 rounded-full bg-blue-500 flex items-center justify-center shadow-md ring-4 ring-blue-100 animate-pulse">
            <PlayCircle size={22} className="text-white" />
          </div>
        ) : isLocked ? (
          <div className="w-10 h-10 rounded-full bg-slate-100 flex items-center justify-center border-2 border-slate-200">
            <Lock size={18} className="text-slate-400" />
          </div>
        ) : (
          <div className="w-10 h-10 rounded-full bg-white flex items-center justify-center border-2 border-slate-300">
            <Circle size={18} className="text-slate-300" />
          </div>
        )}
      </div>

      {/* Content card */}
      <div className={`p-4 rounded-xl border transition-all ${
        node.isCurrent
          ? "border-blue-300 bg-blue-50/50 shadow-md"
          : node.completed
          ? "border-emerald-200 bg-emerald-50/30"
          : "border-slate-200 bg-white"
      }`}>
        <div className="flex items-start justify-between gap-3 mb-2">
          <div className="flex items-center gap-2">
            <span className={`w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold ${
              node.completed ? "bg-emerald-100 text-emerald-700" :
              node.isCurrent ? "bg-blue-100 text-blue-700" :
              "bg-slate-100 text-slate-500"
            }`}>
              {index + 1}
            </span>
            <h4 className={`font-semibold ${node.completed ? "text-slate-500" : "text-slate-900"}`}>
              {node.title}
            </h4>
          </div>
          <div className="flex items-center gap-2 shrink-0">
            {node.isCurrent && <Badge variant="blue">Current</Badge>}
            <DifficultyBadge level={node.difficulty} />
          </div>
        </div>

        <p className={`text-sm mb-3 ${node.completed ? "text-slate-400" : "text-slate-600"}`}>
          {node.description}
        </p>

        <div className="flex flex-wrap items-center gap-2 mb-3">
          {node.skillsCovered.map((skill) => (
            <Badge key={skill} variant="slate">{skill}</Badge>
          ))}
          <div className="flex items-center gap-1 text-xs text-slate-400">
            <Clock size={12} /> {node.estimatedHours} hrs
          </div>
        </div>

        {node.prerequisites.length > 0 && (
          <div className="text-xs text-slate-400 mb-3">
            <span className="font-medium">Prerequisites: </span>
            {node.prerequisites.map((pid, i) => {
              const prereq = pid;
              return (
                <span key={pid}>
                  {i > 0 && ", "}
                  Step {learningPathIndex(pid)}
                </span>
              );
            })}
          </div>
        )}

        <Button
          variant={node.completed ? "outline" : "primary"}
          size="sm"
          onClick={onToggle}
          disabled={isLocked}
        >
          {node.completed ? (
            <><CheckCircle2 size={16} /> Mark as Incomplete</>
          ) : isLocked ? (
            <><Lock size={16} /> Locked</>
          ) : (
            <><CheckCircle2 size={16} /> Mark as Completed</>
          )}
        </Button>
      </div>

      {/* Connector arrow */}
      {!isLast && (
        <div className="absolute left-5 -bottom-1 transform -translate-x-1/2 text-slate-300">
          <ArrowDown size={14} />
        </div>
      )}
    </div>
  );
}

function learningPathIndex(id: string): number {
  // Simple helper to show prerequisite step numbers
  const pathMap: Record<string, number> = {
    "python-basics": 1,
    "python-oop": 2,
    "data-structures": 3,
    "statistics": 4,
    "probability": 5,
    "numpy-pandas": 6,
    "ml-basics": 7,
    "ml-algorithms": 8,
    "ml-project": 9,
    "ds-project": 6,
    "ai-project": 6,
    "project": 3,
  };
  return pathMap[id] || 0;
}
